# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/workspace/xmlrpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/workspace/xmlrpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/workspace/xmlrpc/CMakeFiles /home/chris/workspace/xmlrpc/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/workspace/xmlrpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XmlRpc

# Build rule for target.
XmlRpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 XmlRpc
.PHONY : XmlRpc

# fast build rule for target.
XmlRpc/fast:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/build
.PHONY : XmlRpc/fast

#=============================================================================
# Target rules for targets named FileClient

# Build rule for target.
FileClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileClient
.PHONY : FileClient

# fast build rule for target.
FileClient/fast:
	$(MAKE) -f test/CMakeFiles/FileClient.dir/build.make test/CMakeFiles/FileClient.dir/build
.PHONY : FileClient/fast

#=============================================================================
# Target rules for targets named HelloClient

# Build rule for target.
HelloClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloClient
.PHONY : HelloClient

# fast build rule for target.
HelloClient/fast:
	$(MAKE) -f test/CMakeFiles/HelloClient.dir/build.make test/CMakeFiles/HelloClient.dir/build
.PHONY : HelloClient/fast

#=============================================================================
# Target rules for targets named HelloServer

# Build rule for target.
HelloServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloServer
.PHONY : HelloServer

# fast build rule for target.
HelloServer/fast:
	$(MAKE) -f test/CMakeFiles/HelloServer.dir/build.make test/CMakeFiles/HelloServer.dir/build
.PHONY : HelloServer/fast

#=============================================================================
# Target rules for targets named TestBase64Client

# Build rule for target.
TestBase64Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestBase64Client
.PHONY : TestBase64Client

# fast build rule for target.
TestBase64Client/fast:
	$(MAKE) -f test/CMakeFiles/TestBase64Client.dir/build.make test/CMakeFiles/TestBase64Client.dir/build
.PHONY : TestBase64Client/fast

#=============================================================================
# Target rules for targets named TestBase64Server

# Build rule for target.
TestBase64Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestBase64Server
.PHONY : TestBase64Server

# fast build rule for target.
TestBase64Server/fast:
	$(MAKE) -f test/CMakeFiles/TestBase64Server.dir/build.make test/CMakeFiles/TestBase64Server.dir/build
.PHONY : TestBase64Server/fast

#=============================================================================
# Target rules for targets named TestEGroupwareSSLClient

# Build rule for target.
TestEGroupwareSSLClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestEGroupwareSSLClient
.PHONY : TestEGroupwareSSLClient

# fast build rule for target.
TestEGroupwareSSLClient/fast:
	$(MAKE) -f test/CMakeFiles/TestEGroupwareSSLClient.dir/build.make test/CMakeFiles/TestEGroupwareSSLClient.dir/build
.PHONY : TestEGroupwareSSLClient/fast

#=============================================================================
# Target rules for targets named TestValues

# Build rule for target.
TestValues: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestValues
.PHONY : TestValues

# fast build rule for target.
TestValues/fast:
	$(MAKE) -f test/CMakeFiles/TestValues.dir/build.make test/CMakeFiles/TestValues.dir/build
.PHONY : TestValues/fast

#=============================================================================
# Target rules for targets named TestXml

# Build rule for target.
TestXml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestXml
.PHONY : TestXml

# fast build rule for target.
TestXml/fast:
	$(MAKE) -f test/CMakeFiles/TestXml.dir/build.make test/CMakeFiles/TestXml.dir/build
.PHONY : TestXml/fast

#=============================================================================
# Target rules for targets named Validator

# Build rule for target.
Validator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Validator
.PHONY : Validator

# fast build rule for target.
Validator/fast:
	$(MAKE) -f test/CMakeFiles/Validator.dir/build.make test/CMakeFiles/Validator.dir/build
.PHONY : Validator/fast

src/XmlRpcClient.o: src/XmlRpcClient.cpp.o
.PHONY : src/XmlRpcClient.o

# target to build an object file
src/XmlRpcClient.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcClient.cpp.o
.PHONY : src/XmlRpcClient.cpp.o

src/XmlRpcClient.i: src/XmlRpcClient.cpp.i
.PHONY : src/XmlRpcClient.i

# target to preprocess a source file
src/XmlRpcClient.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcClient.cpp.i
.PHONY : src/XmlRpcClient.cpp.i

src/XmlRpcClient.s: src/XmlRpcClient.cpp.s
.PHONY : src/XmlRpcClient.s

# target to generate assembly for a file
src/XmlRpcClient.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcClient.cpp.s
.PHONY : src/XmlRpcClient.cpp.s

src/XmlRpcDispatch.o: src/XmlRpcDispatch.cpp.o
.PHONY : src/XmlRpcDispatch.o

# target to build an object file
src/XmlRpcDispatch.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcDispatch.cpp.o
.PHONY : src/XmlRpcDispatch.cpp.o

src/XmlRpcDispatch.i: src/XmlRpcDispatch.cpp.i
.PHONY : src/XmlRpcDispatch.i

# target to preprocess a source file
src/XmlRpcDispatch.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcDispatch.cpp.i
.PHONY : src/XmlRpcDispatch.cpp.i

src/XmlRpcDispatch.s: src/XmlRpcDispatch.cpp.s
.PHONY : src/XmlRpcDispatch.s

# target to generate assembly for a file
src/XmlRpcDispatch.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcDispatch.cpp.s
.PHONY : src/XmlRpcDispatch.cpp.s

src/XmlRpcServer.o: src/XmlRpcServer.cpp.o
.PHONY : src/XmlRpcServer.o

# target to build an object file
src/XmlRpcServer.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServer.cpp.o
.PHONY : src/XmlRpcServer.cpp.o

src/XmlRpcServer.i: src/XmlRpcServer.cpp.i
.PHONY : src/XmlRpcServer.i

# target to preprocess a source file
src/XmlRpcServer.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServer.cpp.i
.PHONY : src/XmlRpcServer.cpp.i

src/XmlRpcServer.s: src/XmlRpcServer.cpp.s
.PHONY : src/XmlRpcServer.s

# target to generate assembly for a file
src/XmlRpcServer.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServer.cpp.s
.PHONY : src/XmlRpcServer.cpp.s

src/XmlRpcServerConnection.o: src/XmlRpcServerConnection.cpp.o
.PHONY : src/XmlRpcServerConnection.o

# target to build an object file
src/XmlRpcServerConnection.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerConnection.cpp.o
.PHONY : src/XmlRpcServerConnection.cpp.o

src/XmlRpcServerConnection.i: src/XmlRpcServerConnection.cpp.i
.PHONY : src/XmlRpcServerConnection.i

# target to preprocess a source file
src/XmlRpcServerConnection.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerConnection.cpp.i
.PHONY : src/XmlRpcServerConnection.cpp.i

src/XmlRpcServerConnection.s: src/XmlRpcServerConnection.cpp.s
.PHONY : src/XmlRpcServerConnection.s

# target to generate assembly for a file
src/XmlRpcServerConnection.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerConnection.cpp.s
.PHONY : src/XmlRpcServerConnection.cpp.s

src/XmlRpcServerMethod.o: src/XmlRpcServerMethod.cpp.o
.PHONY : src/XmlRpcServerMethod.o

# target to build an object file
src/XmlRpcServerMethod.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerMethod.cpp.o
.PHONY : src/XmlRpcServerMethod.cpp.o

src/XmlRpcServerMethod.i: src/XmlRpcServerMethod.cpp.i
.PHONY : src/XmlRpcServerMethod.i

# target to preprocess a source file
src/XmlRpcServerMethod.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerMethod.cpp.i
.PHONY : src/XmlRpcServerMethod.cpp.i

src/XmlRpcServerMethod.s: src/XmlRpcServerMethod.cpp.s
.PHONY : src/XmlRpcServerMethod.s

# target to generate assembly for a file
src/XmlRpcServerMethod.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcServerMethod.cpp.s
.PHONY : src/XmlRpcServerMethod.cpp.s

src/XmlRpcSocket.o: src/XmlRpcSocket.cpp.o
.PHONY : src/XmlRpcSocket.o

# target to build an object file
src/XmlRpcSocket.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSocket.cpp.o
.PHONY : src/XmlRpcSocket.cpp.o

src/XmlRpcSocket.i: src/XmlRpcSocket.cpp.i
.PHONY : src/XmlRpcSocket.i

# target to preprocess a source file
src/XmlRpcSocket.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSocket.cpp.i
.PHONY : src/XmlRpcSocket.cpp.i

src/XmlRpcSocket.s: src/XmlRpcSocket.cpp.s
.PHONY : src/XmlRpcSocket.s

# target to generate assembly for a file
src/XmlRpcSocket.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSocket.cpp.s
.PHONY : src/XmlRpcSocket.cpp.s

src/XmlRpcSource.o: src/XmlRpcSource.cpp.o
.PHONY : src/XmlRpcSource.o

# target to build an object file
src/XmlRpcSource.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSource.cpp.o
.PHONY : src/XmlRpcSource.cpp.o

src/XmlRpcSource.i: src/XmlRpcSource.cpp.i
.PHONY : src/XmlRpcSource.i

# target to preprocess a source file
src/XmlRpcSource.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSource.cpp.i
.PHONY : src/XmlRpcSource.cpp.i

src/XmlRpcSource.s: src/XmlRpcSource.cpp.s
.PHONY : src/XmlRpcSource.s

# target to generate assembly for a file
src/XmlRpcSource.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcSource.cpp.s
.PHONY : src/XmlRpcSource.cpp.s

src/XmlRpcUtil.o: src/XmlRpcUtil.cpp.o
.PHONY : src/XmlRpcUtil.o

# target to build an object file
src/XmlRpcUtil.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcUtil.cpp.o
.PHONY : src/XmlRpcUtil.cpp.o

src/XmlRpcUtil.i: src/XmlRpcUtil.cpp.i
.PHONY : src/XmlRpcUtil.i

# target to preprocess a source file
src/XmlRpcUtil.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcUtil.cpp.i
.PHONY : src/XmlRpcUtil.cpp.i

src/XmlRpcUtil.s: src/XmlRpcUtil.cpp.s
.PHONY : src/XmlRpcUtil.s

# target to generate assembly for a file
src/XmlRpcUtil.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcUtil.cpp.s
.PHONY : src/XmlRpcUtil.cpp.s

src/XmlRpcValue.o: src/XmlRpcValue.cpp.o
.PHONY : src/XmlRpcValue.o

# target to build an object file
src/XmlRpcValue.cpp.o:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcValue.cpp.o
.PHONY : src/XmlRpcValue.cpp.o

src/XmlRpcValue.i: src/XmlRpcValue.cpp.i
.PHONY : src/XmlRpcValue.i

# target to preprocess a source file
src/XmlRpcValue.cpp.i:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcValue.cpp.i
.PHONY : src/XmlRpcValue.cpp.i

src/XmlRpcValue.s: src/XmlRpcValue.cpp.s
.PHONY : src/XmlRpcValue.s

# target to generate assembly for a file
src/XmlRpcValue.cpp.s:
	$(MAKE) -f CMakeFiles/XmlRpc.dir/build.make CMakeFiles/XmlRpc.dir/src/XmlRpcValue.cpp.s
.PHONY : src/XmlRpcValue.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... XmlRpc"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FileClient"
	@echo "... HelloClient"
	@echo "... HelloServer"
	@echo "... TestBase64Client"
	@echo "... TestBase64Server"
	@echo "... TestEGroupwareSSLClient"
	@echo "... TestValues"
	@echo "... TestXml"
	@echo "... Validator"
	@echo "... src/XmlRpcClient.o"
	@echo "... src/XmlRpcClient.i"
	@echo "... src/XmlRpcClient.s"
	@echo "... src/XmlRpcDispatch.o"
	@echo "... src/XmlRpcDispatch.i"
	@echo "... src/XmlRpcDispatch.s"
	@echo "... src/XmlRpcServer.o"
	@echo "... src/XmlRpcServer.i"
	@echo "... src/XmlRpcServer.s"
	@echo "... src/XmlRpcServerConnection.o"
	@echo "... src/XmlRpcServerConnection.i"
	@echo "... src/XmlRpcServerConnection.s"
	@echo "... src/XmlRpcServerMethod.o"
	@echo "... src/XmlRpcServerMethod.i"
	@echo "... src/XmlRpcServerMethod.s"
	@echo "... src/XmlRpcSocket.o"
	@echo "... src/XmlRpcSocket.i"
	@echo "... src/XmlRpcSocket.s"
	@echo "... src/XmlRpcSource.o"
	@echo "... src/XmlRpcSource.i"
	@echo "... src/XmlRpcSource.s"
	@echo "... src/XmlRpcUtil.o"
	@echo "... src/XmlRpcUtil.i"
	@echo "... src/XmlRpcUtil.s"
	@echo "... src/XmlRpcValue.o"
	@echo "... src/XmlRpcValue.i"
	@echo "... src/XmlRpcValue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

